### ISSUE TITLE
The semantic-release is broken

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/hibernate-adapter#11]
Maven shows we already released v1.0.0 in Jul, 2020: https://mvnrepository.com/artifact/org.casbin/hibernate-adapter

![image](https://user-images.githubusercontent.com/3787410/111028770-b9c7a700-8433-11eb-864f-fb2e5952167b.png)

But we again release v1.0.0 on GitHub: https://github.com/jcasbin/hibernate-adapter/releases/tag/v1.0.0

![image](https://user-images.githubusercontent.com/3787410/111028781-cba94a00-8433-11eb-8312-1e64b498015d.png)

And this message: https://github.com/jcasbin/hibernate-adapter/issues/10

**Comment by hsluoyz** [comment]
@shy1st

**Comment by shy1st** [comment]
@hsluoyz 
I fix this bug. 
I release the v1.0.1. 
https://github.com/jcasbin/hibernate-adapter/issues/10 this issue has already closed.

**Comment by hsluoyz** [comment]
@shy1st great, thanks!
