### ISSUE TITLE
casbin_rule table not created automatically when using Datasource constructor

### ISSUE THREAD

**Issue by jaskarnshergillCE** [jcasbin/hibernate-adapter#18]
Correct me if I'm wrong, but I took a look at the `HibernateAdapter` class code and it seems it doesn't automatically create a `casbin_rule` table if we use the Datasource constructor, `new HibernateAdapter(DataSource dataSource)` . It seems like `databaseProductName` is not set to trigger the code in createTable().

I know the `jdbc-adapter` creates the table automatically. I was using that adapter before, but it's causing some issues with my app that already uses hibernate, so I'm using the `hibernate-adapter` instead.

**Comment by hsluoyz** [comment]
@tangyang9464 @imp2002

**Comment by hsluoyz** [comment]
@jaskarnshergillCE can you make a PR to fix it?

**Comment by jaskarnshergillCE** [comment]
@hsluoyz sure, I can make an attempt. Please let me know of any PR guidelines you expect.

**Comment by happenedIn** [comment]
@hsluoyz sorry my mistake. The database table is created when using Datasource adapter. I'm using MariaDB which is not supported by hibernate-adapter.
