### ISSUE TITLE
Add README, badges, CI, code coverage, Maven package

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/hibernate-adapter#2]
@tldyl please do it.

**Comment by hsluoyz** [comment]
@tldyl why is this closed? Has it been finished by PR?

**Comment by tldyl** [comment]
I've added it.

**Comment by hsluoyz** [comment]
But none of the badges are working. You are supposed to make it work.

![image](https://user-images.githubusercontent.com/3787410/88446664-81e90080-ce5e-11ea-971f-d5fba145dbe0.png)

**Comment by hsluoyz** [comment]
And make sure you create PR for me to review (the PR will also fix this issue), instead of directly committing to master.

**Comment by hsluoyz** [comment]
@tldyl add this adapter to: https://casbin.org/docs/en/adapters#supported-adapters

**Comment by tldyl** [comment]
Fixed by: #3
