### ISSUE TITLE
Datasource

### ISSUE THREAD

**Issue by uPagge** [jcasbin/hibernate-adapter#5]
`Adapter adapter = new HibernateAdapter(DRIVER, URL, USERNAME, PASSWORD, true);`

Why not make the constructor accept a Datasource?

**Comment by hsluoyz** [comment]
@uPagge thanks for the advice?

@shy1st I think we can add a constructor for datasource arg too like the jdbc-adapter: https://github.com/jcasbin/jdbc-adapter

**Comment by shy1st** [comment]
@uPagge Excuse me, do you want this construction method？
![捕获](https://user-images.githubusercontent.com/34126552/108371393-abbda680-7238-11eb-82b7-e7f85fcc0a5a.PNG)

**Comment by uPagge** [comment]
Yes that would be great

**Comment by hsluoyz** [comment]
@uPagge we are not very clear about how to implement sucha constructor, can you explain a little? Or even a PR would be great!

**Comment by uPagge** [comment]
Unfortunately I'm not that good: D

But I know where it is possible to spy on. Liquibase uses this, but not in the constructor is true. Perhaps the sources of Liquibase will help you understand.

![изображение](https://user-images.githubusercontent.com/40397740/108377704-58862c80-7215-11eb-92f1-0a359a94695f.png)

**Comment by shy1st** [comment]
Sorry, we can get URL, driver and user name through datasource, but we can't get password. Can you provide password in the construction method? Or do you have any other ideas? @uPagge

**Comment by shy1st** [comment]
@uPagge Maybe the ConnectionProvider can set the datasource, but how to build SessionFactory through ConnectionProvider is a problem.May I ask you what is your idea?

**Comment by uPagge** [comment]
Well, my idea is that in the world of spring boot applications, database connection for libraries compatible with spring happens through this very datasource. Unfortunately, I do not know how to do this, and therefore I cannot tell. Just suggested an idea for improving convenience))

**Comment by shy1st** [comment]
@fangzhengjin Excuse me, may I ask you your idea?

**Comment by fangzhengjin** [comment]
@uPagge Do you use casbin in Spring Boot ?

**Comment by fangzhengjin** [comment]
> @fangzhengjin Excuse me, may I ask you your idea?

I think we can set the data source through the `hibernate.connection.datasource` configuration.
see: [database-connectionprovider-datasource](https://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#database-connectionprovider-datasource)

**Comment by shy1st** [comment]
@fangzhengjin Thank you for your advice!

**Comment by hsluoyz** [comment]
@shy1st plz make a new release on both Maven and GitHub.
